"""Native sandbox lifecycle, separate from the Harness's tool dispatch protocol."""
from typing import Protocol

from forge.sandbox.capabilities import CapabilityReport


class SandboxBackend(Protocol):
    async def probe(self) -> CapabilityReport: ...
    async def prepare(self, policy) -> dict: ...
    async def execute(self, execution_id: str, command: dict) -> dict: ...
    async def status(self, execution_id: str) -> dict: ...
    async def cancel(self, execution_id: str, reason: str, deadline_utc: str) -> dict: ...
    async def close(self) -> dict: ...
