/** Build-time AJV standalone validators: no Function/eval in the browser. */
import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve,dirname} from 'node:path';
import {Ajv2020} from 'ajv/dist/2020.js';
import formats from 'ajv-formats';
import standalone from 'ajv/dist/standalone/index.js';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const bundle=JSON.parse(readFileSync(resolve(root,'packages/contracts/src/generated/schemas.json'),'utf8'));
const ajv=new Ajv2020({strict:false,allErrors:false,validateFormats:true,ownProperties:true,inlineRefs:false,code:{source:true,esm:true}});
formats(ajv);
for(const schema of Object.values(bundle.schemas))ajv.addSchema(schema);
const entries=Object.entries(bundle.schemas);
const names=Object.fromEntries(entries.map(([,schema],index)=>['v'+index,schema.$id]));
let code=standalone(ajv,names);
const modules=[...new Set([...code.matchAll(/require\("([^"]+)"\)/g)].map(match=>match[1]))];
let imports='';
for(const [index,module] of modules.entries()){
  if(!['ajv-formats/dist/formats','ajv/dist/runtime/ucs2length','ajv/dist/runtime/equal'].includes(module))
    throw new Error('Standalone generator introduced an unreviewed runtime import: '+module);
  imports+='import runtime'+index+' from '+JSON.stringify(module+'.js')+';\n';
  code=code.replaceAll('require('+JSON.stringify(module)+')','runtime'+index);
}
code='// @ts-nocheck\n// Generated by scripts/build_browser_contracts.mjs; do not edit.\n'+imports+code+
  '\nexport const validators={'+entries.map(([name],index)=>JSON.stringify(name)+':v'+index).join(',')+'};\n';
const path=resolve(root,'packages/contracts/src/generated/browser_validators.ts');
if(process.argv.includes('--check')){
  if(readFileSync(path,'utf8').replaceAll('\r\n','\n')!==code)throw new Error('Browser validators drift; run build_browser_contracts.mjs');
}else writeFileSync(path,code,'utf8');
process.stdout.write(JSON.stringify({schemas:entries.length,bytes:Buffer.byteLength(code),runtime_imports:modules})+'\n');
