"""Generate runtime schemas and TypeScript types from contracts/v1; --check is read-only."""
import argparse
import json
from pathlib import Path
import re

from jsonschema import Draft202012Validator

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / 'contracts/v1'
HEADER = '// Generated by scripts/check_contracts.py; edit contracts/v1 instead.\n'


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f'Duplicate contract key: {key}')
        result[key] = value
    return result


def read_contract(path):
    return json.loads(path.read_text(encoding='utf-8'), object_pairs_hook=unique_object)


def type_name(name):
    return ''.join(part[:1].upper() + part[1:] for part in re.split(r'[^a-zA-Z0-9]+', name))


def ts_type(schema):
    if '$ref' in schema:
        reference = schema['$ref'].split(':')[-1]
        if '#/$defs/' in reference:
            reference = reference.split('#/$defs/')[1]
        return type_name(reference)
    if 'const' in schema:
        return json.dumps(schema['const'], ensure_ascii=False)
    if 'enum' in schema:
        return ' | '.join(json.dumps(value, ensure_ascii=False) for value in schema['enum'])
    for combinator in ('anyOf', 'oneOf'):
        if combinator in schema:
            return ' | '.join('(' + ts_type(branch) + ')' for branch in schema[combinator])
    kind = schema.get('type')
    if kind == 'object':
        properties = schema.get('properties', {})
        if not properties:
            if schema.get('additionalProperties') is False:
                return '{ [key: string]: never }'
            return '{ [key: string]: ' + (ts_type(schema['additionalProperties']) if isinstance(schema.get('additionalProperties'), dict) else 'JSONValue') + ' }'
        fields = [json.dumps(key) + ('' if key in schema.get('required', []) else '?') + ': ' + ts_type(value)
                  for key, value in properties.items()]
        return '{ ' + '; '.join(fields) + ' }'
    if kind == 'array':
        return 'Array<' + ts_type(schema['items']) + '>'
    if kind in ('integer', 'number'):
        return 'number'
    if kind in ('string', 'boolean', 'null'):
        return kind
    return 'JSONValue'


def generated_files():
    schemas = {}
    for path in sorted((BASE / 'schemas').glob('*.schema.json')):
        schema = read_contract(path)
        Draft202012Validator.check_schema(schema)
        schemas[path.name.removesuffix('.schema.json')] = schema
    methods = read_contract(BASE / 'methods.json')['methods']
    for name, method in methods.items():
        for direction in ('request', 'result'):
            key = method[direction + '_schema']
            if key != name + '.' + direction or key not in schemas['method-payloads']['$defs']:
                raise ValueError(f'Missing method contract: {key}')
            schemas[key] = {'$schema': 'https://json-schema.org/draft/2020-12/schema',
                            '$id': 'urn:forgecode:contracts:v1:' + key,
                            '$ref': schemas['method-payloads']['$id'] + '#/$defs/' + key}
    bridge = read_contract(BASE / 'bridge-methods.json')['methods']
    events = read_contract(BASE / 'events.json')['events']
    for name, method in bridge.items():
        for direction in ('request', 'result'):
            key = method[direction + '_schema']
            schemas[key] = {'$schema': 'https://json-schema.org/draft/2020-12/schema', '$id': 'urn:forgecode:contracts:v1:' + key,
                            '$ref': schemas['bridge-payloads']['$id'] + '#/$defs/' + name + '.' + direction}
    for name, event in events.items():
        key = event['payload_schema']
        schemas[key] = {'$schema': 'https://json-schema.org/draft/2020-12/schema', '$id': 'urn:forgecode:contracts:v1:' + key,
                        '$ref': schemas['event-payloads']['$id'] + '#/$defs/' + name}
    bundle = {'schema_version': 'forge.generated.contracts.v1', 'methods': methods, 'bridge_methods': bridge, 'events': events, 'schemas': schemas}
    encoded = json.dumps(bundle, ensure_ascii=False, sort_keys=True, indent=2) + '\n'
    declarations = [HEADER, 'export type JSONValue = null | boolean | number | string | JSONValue[] | { [key: string]: JSONValue };\n']
    for name, schema in sorted(schemas.items()):
        if name in ('method-payloads', 'bridge-payloads', 'event-payloads') or name.endswith(('.request', '.result')) or name.startswith('event.'):
            continue
        declarations.append(f'export type {type_name(name)} = {ts_type(schema)};\n')
    for name, schema in schemas['method-payloads']['$defs'].items():
        declarations.append(f'export type {type_name(name)} = {ts_type(schema)};\n')
    for name, schema in schemas['bridge-payloads']['$defs'].items():
        declarations.append(f'export type {type_name("bridge." + name)} = {ts_type(schema)};\n')
    for name, schema in schemas['event-payloads']['$defs'].items():
        declarations.append(f'export type {type_name("event." + name)} = {ts_type(schema)};\n')
    errors = schemas['business-error']['properties']['data']['properties']['kind']['enum']
    declarations.append('export const ERROR_KINDS = ' + json.dumps(errors) + ' as const;\nexport type ErrorKind = typeof ERROR_KINDS[number];\n')
    declarations.append('export interface MethodMap {\n')
    for name in methods:
        declarations.append(f'  "{name}": {{ request: {type_name(name + ".request")}; result: {type_name(name + ".result")} }};\n')
    declarations.append('}\nexport type MethodName = keyof MethodMap;\n')
    return {ROOT / 'forge/application/_generated_contracts.json': encoded,
            ROOT / 'packages/contracts/src/generated/schemas.json': encoded,
            ROOT / 'packages/contracts/src/generated/types.ts': ''.join(declarations)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    drift = []
    outputs = generated_files()
    for path, content in outputs.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding='utf-8') != content:
                drift.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8')
    print(json.dumps({'status': 'fail' if drift else 'pass', 'generated_files': len(outputs), 'drift': drift}))
    return 1 if drift else 0


if __name__ == '__main__':
    raise SystemExit(main())
